# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replicas_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replicas_response.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17replicas_response.proto\"W\n\x07Replica\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x10\n\x08\x63hunk_id\x18\x04 \x01(\x05\x12\x12\n\nis_primary\x18\x05 \x01(\x08\")\n\x0bReplicaList\x12\x1a\n\x08replicas\x18\x01 \x03(\x0b\x32\x08.Replicab\x06proto3')
)




_REPLICA = _descriptor.Descriptor(
  name='Replica',
  full_name='Replica',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Replica.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Replica.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Replica.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_id', full_name='Replica.chunk_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_primary', full_name='Replica.is_primary', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=114,
)


_REPLICALIST = _descriptor.Descriptor(
  name='ReplicaList',
  full_name='ReplicaList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replicas', full_name='ReplicaList.replicas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=157,
)

_REPLICALIST.fields_by_name['replicas'].message_type = _REPLICA
DESCRIPTOR.message_types_by_name['Replica'] = _REPLICA
DESCRIPTOR.message_types_by_name['ReplicaList'] = _REPLICALIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Replica = _reflection.GeneratedProtocolMessageType('Replica', (_message.Message,), dict(
  DESCRIPTOR = _REPLICA,
  __module__ = 'replicas_response_pb2'
  # @@protoc_insertion_point(class_scope:Replica)
  ))
_sym_db.RegisterMessage(Replica)

ReplicaList = _reflection.GeneratedProtocolMessageType('ReplicaList', (_message.Message,), dict(
  DESCRIPTOR = _REPLICALIST,
  __module__ = 'replicas_response_pb2'
  # @@protoc_insertion_point(class_scope:ReplicaList)
  ))
_sym_db.RegisterMessage(ReplicaList)


# @@protoc_insertion_point(module_scope)
