# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfs.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\"9\n\x0b\x46ileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0c\n\x04size\x18\x03 \x01(\x03\"E\n\x07Replica\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x12\n\nis_primary\x18\x05 \x01(\x08\"5\n\x05\x43hunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\x05\x12\x1a\n\x08replicas\x18\x02 \x03(\x0b\x32\x08.Replica\"4\n\tChunkList\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\x06.Chunk\"2\n\x0c\x46ileResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66iledata\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=13
  _globals['_FILEREQUEST']._serialized_end=70
  _globals['_REPLICA']._serialized_start=72
  _globals['_REPLICA']._serialized_end=141
  _globals['_CHUNK']._serialized_start=143
  _globals['_CHUNK']._serialized_end=196
  _globals['_CHUNKLIST']._serialized_start=198
  _globals['_CHUNKLIST']._serialized_end=250
  _globals['_FILERESPONSE']._serialized_start=252
  _globals['_FILERESPONSE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
