version: '3.9'

services:
  server_container:
    build:
      context: .
      dockerfile: Dockerfile.all
    ports:
      - "9001:9001"
    command: ["sh", "-c", "cd server && ./server"]

  client_container:
    build:
      context: .
      dockerfile: Dockerfile.all
    # command: ["sh", "-c", "cd client && sleep 2 && ./client write alphabet && sleep 2 && ./client read alphabet"]
    command: ["sh", "-c", "cd client && sleep 2 && ./client write ala && sleep 2 && ./client read ala"]
    depends_on:
      - server_container

  replica_container_0:
    build:
      context: .
      dockerfile: Dockerfile.all
    ports:
      - "8080:8080"
    command: ["sh", "-c", "cd replica && ./replica 8080"]
    # command: ["sh", "-c", "(cd replica && ./replica 8080 &) && PID=$! && sleep 1 && kill -9 $PID"]
    # command: ["sh", "-c", "cd replica && ./replica 8080 && sleep 1 && kill -9 -1"]

  replica_container_1:
    build:
      context: .
      dockerfile: Dockerfile.all
    ports:
      - "8081:8081"
    command: ["sh", "-c", "cd replica && ./replica 8081"]

  replica_container_2:
    build:
      context: .
      dockerfile: Dockerfile.all
    ports:
      - "8082:8082"
    command: ["sh", "-c", "cd replica && ./replica 8082"]

  replica_container_3:
    build:
      context: .
      dockerfile: Dockerfile.all
    ports:
      - "8083:8083"
    command: ["sh", "-c", "cd replica && ./replica 8083"]

  replica_container_4:
    build:
      context: .
      dockerfile: Dockerfile.all
    ports:
      - "8084:8084"
    command: ["sh", "-c", "cd replica && ./replica 8084"]
