version: '3.9'

services:
  server_container:
    build:
      context: .
      dockerfile: Dockerfile.all
    command: ["sh", "-c", "cd server && ./server"]

  client_container:
    build:
      context: .
      dockerfile: Dockerfile.all
    command: ["sh", "-c", "cd client && sleep 3 && ./client read ala"]
    depends_on:
      - server_container

  replica_container_1:
    build:
      context: .
      dockerfile: Dockerfile.all
    command: ["sh", "-c", "cd replica && ./replica"]

  replica_container_2:
    build:
      context: .
      dockerfile: Dockerfile.all
    command: ["sh", "-c", "cd replica && ./replica"]
