version: '3.9'

services:
  server_container:
    build:
      context: .
      dockerfile: Dockerfile-write.all
    command: ["sh", "-c", "cd server && ./server"]

  client_container:
    build:
      context: .
      dockerfile: Dockerfile-write.all
    command: ["sh", "-c", "cd client && sleep 3 && ./client write komar.txt"]
    depends_on:
      - server_container
      - replica_container_1
      - replica_container_2

  replica_container_1:
    build:
      context: .
      dockerfile: Dockerfile-write.all
    command: ["sh", "-c", "cd replica && ./replica 8080"]
  
  replica_container_2:
    build:
      context: .
      dockerfile: Dockerfile-write.all
    command: ["sh", "-c", "cd replica && ./replica 8081"]
