FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    protobuf-c-compiler \
    libprotobuf-c-dev \
    libglib2.0-dev \
    cmake \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY . /

RUN bash setup.bash && \
    rm -rf build && \
    mkdir -p build/replica/data_replica1/8080/chunks build/replica/data_replica1/8081/chunks && \
    cd build && \
    cmake .. && \
    make && \
    cp ../data_client/alphabet client/alphabet

WORKDIR /build
