/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dfs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dfs.pb-c.h"
void   file_request__init
                     (FileRequest         *message)
{
  static const FileRequest init_value = FILE_REQUEST__INIT;
  *message = init_value;
}
size_t file_request__get_packed_size
                     (const FileRequest *message)
{
  assert(message->base.descriptor == &file_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_request__pack
                     (const FileRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_request__pack_to_buffer
                     (const FileRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileRequest *
       file_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileRequest *)
     protobuf_c_message_unpack (&file_request__descriptor,
                                allocator, len, data);
}
void   file_request__free_unpacked
                     (FileRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   replica__init
                     (Replica         *message)
{
  static const Replica init_value = REPLICA__INIT;
  *message = init_value;
}
size_t replica__get_packed_size
                     (const Replica *message)
{
  assert(message->base.descriptor == &replica__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t replica__pack
                     (const Replica *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &replica__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t replica__pack_to_buffer
                     (const Replica *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &replica__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Replica *
       replica__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Replica *)
     protobuf_c_message_unpack (&replica__descriptor,
                                allocator, len, data);
}
void   replica__free_unpacked
                     (Replica *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &replica__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chunk__init
                     (Chunk         *message)
{
  static const Chunk init_value = CHUNK__INIT;
  *message = init_value;
}
size_t chunk__get_packed_size
                     (const Chunk *message)
{
  assert(message->base.descriptor == &chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chunk__pack
                     (const Chunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chunk__pack_to_buffer
                     (const Chunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chunk *
       chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chunk *)
     protobuf_c_message_unpack (&chunk__descriptor,
                                allocator, len, data);
}
void   chunk__free_unpacked
                     (Chunk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chunk_list__init
                     (ChunkList         *message)
{
  static const ChunkList init_value = CHUNK_LIST__INIT;
  *message = init_value;
}
size_t chunk_list__get_packed_size
                     (const ChunkList *message)
{
  assert(message->base.descriptor == &chunk_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chunk_list__pack
                     (const ChunkList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chunk_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chunk_list__pack_to_buffer
                     (const ChunkList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chunk_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChunkList *
       chunk_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChunkList *)
     protobuf_c_message_unpack (&chunk_list__descriptor,
                                allocator, len, data);
}
void   chunk_list__free_unpacked
                     (ChunkList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chunk_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chunk_request__init
                     (ChunkRequest         *message)
{
  static const ChunkRequest init_value = CHUNK_REQUEST__INIT;
  *message = init_value;
}
size_t chunk_request__get_packed_size
                     (const ChunkRequest *message)
{
  assert(message->base.descriptor == &chunk_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chunk_request__pack
                     (const ChunkRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chunk_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chunk_request__pack_to_buffer
                     (const ChunkRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chunk_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChunkRequest *
       chunk_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChunkRequest *)
     protobuf_c_message_unpack (&chunk_request__descriptor,
                                allocator, len, data);
}
void   chunk_request__free_unpacked
                     (ChunkRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chunk_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_chunk__init
                     (WriteChunk         *message)
{
  static const WriteChunk init_value = WRITE_CHUNK__INIT;
  *message = init_value;
}
size_t write_chunk__get_packed_size
                     (const WriteChunk *message)
{
  assert(message->base.descriptor == &write_chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_chunk__pack
                     (const WriteChunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &write_chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_chunk__pack_to_buffer
                     (const WriteChunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &write_chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteChunk *
       write_chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteChunk *)
     protobuf_c_message_unpack (&write_chunk__descriptor,
                                allocator, len, data);
}
void   write_chunk__free_unpacked
                     (WriteChunk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &write_chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file_response__init
                     (FileResponse         *message)
{
  static const FileResponse init_value = FILE_RESPONSE__INIT;
  *message = init_value;
}
size_t file_response__get_packed_size
                     (const FileResponse *message)
{
  assert(message->base.descriptor == &file_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_response__pack
                     (const FileResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_response__pack_to_buffer
                     (const FileResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileResponse *
       file_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileResponse *)
     protobuf_c_message_unpack (&file_response__descriptor,
                                allocator, len, data);
}
void   file_response__free_unpacked
                     (FileResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   commit_chunk__init
                     (CommitChunk         *message)
{
  static const CommitChunk init_value = COMMIT_CHUNK__INIT;
  *message = init_value;
}
size_t commit_chunk__get_packed_size
                     (const CommitChunk *message)
{
  assert(message->base.descriptor == &commit_chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t commit_chunk__pack
                     (const CommitChunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &commit_chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t commit_chunk__pack_to_buffer
                     (const CommitChunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &commit_chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CommitChunk *
       commit_chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CommitChunk *)
     protobuf_c_message_unpack (&commit_chunk__descriptor,
                                allocator, len, data);
}
void   commit_chunk__free_unpacked
                     (CommitChunk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &commit_chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor file_request__field_descriptors[3] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FileRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(FileRequest, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(FileRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_request__field_indices_by_name[] = {
  1,   /* field[1] = offset */
  0,   /* field[0] = path */
  2,   /* field[2] = size */
};
static const ProtobufCIntRange file_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor file_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FileRequest",
  "FileRequest",
  "FileRequest",
  "",
  sizeof(FileRequest),
  3,
  file_request__field_descriptors,
  file_request__field_indices_by_name,
  1,  file_request__number_ranges,
  (ProtobufCMessageInit) file_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor replica__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Replica, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Replica, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Replica, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_primary",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Replica, is_primary),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned replica__field_indices_by_name[] = {
  1,   /* field[1] = ip */
  3,   /* field[3] = is_primary */
  0,   /* field[0] = name */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange replica__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor replica__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Replica",
  "Replica",
  "Replica",
  "",
  sizeof(Replica),
  4,
  replica__field_descriptors,
  replica__field_indices_by_name,
  1,  replica__number_ranges,
  (ProtobufCMessageInit) replica__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chunk__field_descriptors[2] =
{
  {
    "chunk_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Chunk, chunk_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replicas",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Chunk, n_replicas),
    offsetof(Chunk, replicas),
    &replica__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chunk__field_indices_by_name[] = {
  0,   /* field[0] = chunk_id */
  1,   /* field[1] = replicas */
};
static const ProtobufCIntRange chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Chunk",
  "Chunk",
  "Chunk",
  "",
  sizeof(Chunk),
  2,
  chunk__field_descriptors,
  chunk__field_indices_by_name,
  1,  chunk__number_ranges,
  (ProtobufCMessageInit) chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chunk_list__field_descriptors[2] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ChunkList, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunks",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChunkList, n_chunks),
    offsetof(ChunkList, chunks),
    &chunk__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chunk_list__field_indices_by_name[] = {
  1,   /* field[1] = chunks */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange chunk_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chunk_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChunkList",
  "ChunkList",
  "ChunkList",
  "",
  sizeof(ChunkList),
  2,
  chunk_list__field_descriptors,
  chunk_list__field_indices_by_name,
  1,  chunk_list__number_ranges,
  (ProtobufCMessageInit) chunk_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chunk_request__field_descriptors[2] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChunkRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChunkRequest, chunk_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chunk_request__field_indices_by_name[] = {
  1,   /* field[1] = chunk_id */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange chunk_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chunk_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChunkRequest",
  "ChunkRequest",
  "ChunkRequest",
  "",
  sizeof(ChunkRequest),
  2,
  chunk_request__field_descriptors,
  chunk_request__field_indices_by_name,
  1,  chunk_request__number_ranges,
  (ProtobufCMessageInit) chunk_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_chunk__field_descriptors[3] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WriteChunk, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WriteChunk, chunk_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replicas",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WriteChunk, n_replicas),
    offsetof(WriteChunk, replicas),
    &replica__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_chunk__field_indices_by_name[] = {
  1,   /* field[1] = chunk_id */
  0,   /* field[0] = path */
  2,   /* field[2] = replicas */
};
static const ProtobufCIntRange write_chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor write_chunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WriteChunk",
  "WriteChunk",
  "WriteChunk",
  "",
  sizeof(WriteChunk),
  3,
  write_chunk__field_descriptors,
  write_chunk__field_indices_by_name,
  1,  write_chunk__number_ranges,
  (ProtobufCMessageInit) write_chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file_response__field_descriptors[2] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FileResponse, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filedata",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FileResponse, filedata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_response__field_indices_by_name[] = {
  1,   /* field[1] = filedata */
  0,   /* field[0] = filename */
};
static const ProtobufCIntRange file_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor file_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FileResponse",
  "FileResponse",
  "FileResponse",
  "",
  sizeof(FileResponse),
  2,
  file_response__field_descriptors,
  file_response__field_indices_by_name,
  1,  file_response__number_ranges,
  (ProtobufCMessageInit) file_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor commit_chunk__field_descriptors[4] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(CommitChunk, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CommitChunk, chunk_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replicas_success",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CommitChunk, n_replicas_success),
    offsetof(CommitChunk, replicas_success),
    &replica__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replicas_fail",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CommitChunk, n_replicas_fail),
    offsetof(CommitChunk, replicas_fail),
    &replica__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned commit_chunk__field_indices_by_name[] = {
  1,   /* field[1] = chunk_id */
  3,   /* field[3] = replicas_fail */
  2,   /* field[2] = replicas_success */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange commit_chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor commit_chunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CommitChunk",
  "CommitChunk",
  "CommitChunk",
  "",
  sizeof(CommitChunk),
  4,
  commit_chunk__field_descriptors,
  commit_chunk__field_indices_by_name,
  1,  commit_chunk__number_ranges,
  (ProtobufCMessageInit) commit_chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
